# =================================
# = Server
# =================================
server:
   port: 8081

# =================================
# = Spring
# =================================
spring:
   application:
      name: userprofile
   datasource:
      url: jdbc:postgresql://localhost:5432/userprofile_db
      username: admin
      password: root
   jpa:
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
   rabbitmq:
      addresses: amqps://<YOUR>

# =================================
# = RabbitMQ
# =================================
broker:
   queue:
      notification:
         name: default.notification

# =================================
# = Auth
# =================================
token:
   jwt:
      secret: test123
      issuer: ms-userprofile
      expiration: 1

timezone: America/Sao_Paulo